name: 'Pylint Annotator'
author: 'Rodrigo Nogues'
description: 'Annotate PRs with Pylint errors and warnings from Github checks output'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'green'
