name: Python application

on: [push]

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup Pylint annotations
      uses: rodrigo-nogues/pylint-annotations@v1
    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint --output-format=parseable --exit-zero ./violations.py

